### ISSUE TITLE
Section 3 "Core Data Model" clean up

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-model#1311] opened 2023-10-07 03:32 UTC
From the Issue #1285 

> 3.2 Credentials
>
> This talks about claims being "made by" an entity, but 3.1 Claims did not introduce the concept of quoting.
>
> This also shows a "Verifiable Credential Graph" being used as the subject of a claim, which isn't introduced in 3.1.
>
> I see that "proof" is defined as {..."@container": "@graph"}, but if I'm reading https://www.w3.org/TR/json-ld/#graph-containers correctly, that makes its _target_ a graph, not its source.

Some kind of clean-up where concepts relavant to all sub-sections 3.1~3.3 are introduced upfront.

**Comment by iherman** [comment] 2024-02-07 17:58
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-02-07-vcwg#section4-5) on 2024-02-07

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5. Section 3 "Core Data Model" clean up (issue vc-data-model#1311)

_See github issue [vc-data-model#1311](https://github.com/w3c/vc-data-model/issues/1311)._




**Brent Zundel:** its not entirely clear to me what the action is. This was taken from one of the first review from Jeff.  

**Ivan Herman:** This was from October. Since then, this subsection has been re-written with new diagrams and new explanations. I think that the issue is now moot.  

**Manu Sporny:** underscore what ivan said. This has been addressed by previous PRs.  

**Ted Thibodeau Jr.:** I think this is largely addressed but we should go back for a re-review.  

**Brent Zundel:** seems like he is asking for more detail in the introduction.  

**Manu Sporny:** He didn't realize we had solve the graph quoting problem. We have solved it in dataset canonicalization. He was not aware that it was now possible. We should not expose readers to that in the beginning.  

> *Phillip Long:* Like talking when to lawyers should be careful what we ask for... since it's been rewritten anyway (largely) it's addressed.

**Brent Zundel:** proposal is that we think it has been addressed.  

**Ted Thibodeau Jr.:** But this needs to bounce back to Jeffrey.  

**Brent Zundel:** we are going to close as addressed but I don't know if Jeffrey wants us to reach out on each issue. Maybe when we close all of them we can ask for a re-review.  

**Ivan Herman:** Definitely do the latter. So many things have changed as a result of his PRs. Going back individually to each issue doesn't make sense. Best to ask for a new review from scratch if he wants.  

**Brent Zundel:** This will close after call.  

</details>

**Comment by brentzundel** [comment] 2024-02-07 19:34
Closing, per the conversation during the call today.

**Closed by brentzundel** 2024-02-07 19:34 UTC
Labels: post-CR
