### ISSUE TITLE
Normative terminology (e.g. MUST) in sections marked non-normative

### ISSUE THREAD

**Issue by nedmsmith** [w3c/vc-data-model#394] opened 2019-01-23 15:41 UTC
For example Section 4 of the Data Model document.

**Comment by brentzundel** [comment] 2019-03-05 12:56
Decision from F2F in Barcelona:
- [ ] @rhiaro and @ken-ebert to review non-normative sections for normative statements.
- [ ] close this issue

**Comment by ken-ebert** [comment] 2019-03-11 21:57
I have reviewed the usage of MAY, MUST, MUST NOT, RECOMMENDED and SHOULD throughout the non-normative sections of the specification.

I looked at both uppercase and lowercase usage of each term.
My results are :
0 uses of "MAY" or "may" require correction.

1 uses of "MUST" or "must" require correction.
  Section 5.2 Trust Model
    ... "To establish this trust, a credential MUST either:"
    will be changed to 
    ... "To establish this trust, a credential must either:"

0 uses of "MUST NOT" or "must not" require correction.

0 uses of "RECOMMENDED" or "recommended" require correction.

0 uses of "SHOULD" or "should" require correction.

**Comment by msporny** [comment] 2019-03-15 01:33
> 1 uses of "MUST" or "must" require correction.

Fixed in https://github.com/w3c/vc-data-model/commit/bf894cfa426d0de55aa0888c5a6f9783b7f49f66

**Comment by msporny** [comment] 2019-03-15 01:34
> Section 4 of the Data Model document.

Section 4 is a normative section, so MUSTs/SHOULDs/MAYs are ok there. I'm making a pass on the spec to clearly mark non-normative sections in case any are missing the distinction due to edit conflicts.

**Comment by msporny** [comment] 2019-03-15 01:56
Made another pass here -- didn't find any misplaced normative statements in non-normative sections 6d157ca54e192f8461c7d5b87508ce4d4c342e20.

Closing issue. Please re-open if you disagree.

**Comment by rhiaro** [comment] 2019-03-17 22:27
In https://github.com/w3c/vc-data-model/commit/9331c440e4f6a54a0e631efc0eb7aab082fb0e84 I made the following minor editorial fixes:

* Change status of VC-USECASES from FPWD to NOTE.
* Add "atrisk" class to all feature at risk issues.
* Change a "MUST .. optionally" to "MAY" in termsOfUse.
* Mark 5.10 Authorization as non-normative.

And I'm reopening this issue pending resolution (hopefully easy) of the following:

1. This [NOTE](https://w3c.github.io/vc-data-model/#h-note-3) contains normative language:

> This document uses the examples context URI (https://www.w3.org/2018/credentials/examples/v1) 
> for the purposes of demonstrating examples. The examples context URI MUST NOT be used for any 
> other purpose, such as in pilot or production systems. 

I believe the MUST NOT needs to be moved outside of the NOTE, or changed to informative language (probably the former).

2. [Disputs section](https://w3c.github.io/vc-data-model/#disputes):

> A <code>DisputeCredential</code> issued by
> anyone other than the <a>subject</a> should be disregarded by the
> <a>verifier</a>, unless the <a>verifier</a> has some other way of determining

Is this deliberately a lowercase 'should' or ought it be:

> A <code>DisputeCredential</code> issued by
> anyone other than the <a>subject</a> SHOULD be disregarded by the
> <a>verifier</a>, <em>unless</em> the <a>verifier</a> has some other way of determining

3. [6.3 Proof formats](https://w3c.github.io/vc-data-model/#proof-formats) says in the opening paragraph there are no normative statements related to the use proofs, but then goes on to make normative statments about JWTs. "related to the use of" is a little ambiguous so perhaps it should say "This specification does not normatively require any particular digital proof or signature format."

4. There's a bunch of normative language about <code>nonTransferable</code> property in [Subject is the Holder](https://w3c.github.io/vc-data-model/#subject-is-the-holder)

And in more editorial things:

5. Because of respec styling <code>h4</code> and <code>h5</code> the same, the [JWT and JWS considerations](https://w3c.github.io/vc-data-model/#jwt-and-jws-considerations) section appears to be empty (but it just has two subsections).

6. Potential confusion in [Types](https://w3c.github.io/vc-data-model/#types) about the type needing to be a URI, but the examples being strings unless you run a JSON-LD parser in your head as you read the example, which not everyone is gonna (I believe DavidC mentioned this or something similar at the F2F too). I think it can probably be resolved by changing:

> The value of the type property MUST be, or map to, one or more URIs

to 

> The value of the type property MUST be, or map to (via JSON-LD processing of the <code>@context</code> property), one or more URIs

and moving the NOTE at the end of Types up to right after the example?

7. Should the links to [Implementation Guidelines](https://w3c.github.io/vc-imp-guide/) in a couple of notes be a real (informative) reference?

8. In [Content integrity](https://w3c.github.io/vc-data-model/#content-integrity-protection), should Hashlink and IPFS be real (informative) references?

**Comment by ken-ebert** [comment] 2019-03-19 00:24
The CR draft has normative language appearing non-normative sections B.1 Subject is Holder and B.1.1 nonTransferable Property.

**Comment by ken-ebert** [comment] 2019-03-19 20:01
My previous comment is a duplicate of Amy's item 4 (March 17) above.

**Comment by brentzundel** [comment] 2019-03-22 17:39
> 1. This [NOTE](https://w3c.github.io/vc-data-model/#h-note-3) contains normative language:
> 
> > This document uses the examples context URI (https://www.w3.org/2018/credentials/examples/v1)
> > for the purposes of demonstrating examples. The examples context URI MUST NOT be used for any
> > other purpose, such as in pilot or production systems.
> 
> I believe the MUST NOT needs to be moved outside of the NOTE, or changed to informative language (probably the former).
This should be changed to informative language.

> 1. [Disputes section](https://w3c.github.io/vc-data-model/#disputes):
> 
> > A `DisputeCredential` issued by
> > anyone other than the subject should be disregarded by the
> > verifier, unless the verifier has some other way of determining
> 
> Is this deliberately a lowercase 'should' or ought it be:
Yes, this should is deliberately lowercase, as this is related to protocol.

> 1. [6.3 Proof formats](https://w3c.github.io/vc-data-model/#proof-formats) says in the opening paragraph there are no normative statements related to the use proofs, but then goes on to make normative statments about JWTs. "related to the use of" is a little ambiguous so perhaps it should say "This specification does not normatively require any particular digital proof or signature format."
+1

> 1. Should the links to [Implementation Guidelines](https://w3c.github.io/vc-imp-guide/) in a couple of notes be a real (informative) reference?
Yes, I think so.

**Comment by burnburn** [comment] 2019-03-26 15:59
In call today @rhiaro said she would provide a PR.

**Comment by msporny** [comment] 2019-04-06 18:24
Multiple PRs have been approved and merged that are related to this issue. I think we've whittled this particular issue into sawdust at this point. Next step is to get approval from WG to close this issue.

**Comment by stonematt** [comment] 2019-04-16 15:42
Resolved on VCWG call 4/16/2019.
RESOLVED: Multiple non-normative commits and PRs (#475, #499) have been written, reviewed and applied for this issue. The WG does not believe that any more mis-characterized normative terminology appears in non-normative sections. Issue #394 should be closed.

Plan to close in 7days

**Closed** 2019-04-25 14:54 UTC
Labels: Pending 7 Day Close
