### ISSUE TITLE
Consider explicitly allowing/recommending language maps for use in internationalisation.

### ISSUE THREAD

**Issue by anthonycamilleri** [w3c/vc-data-model#1479] opened 2024-04-18 10:56 UTC
In the European context, multilingual credentials are commonplace. The typical use case is to have approx. 30 languages which may be used for a credential-type, with any individual credential being typically expressed in 2-3 languages. For this kind of use case, it makes sense for us to use JSON-LD language indexing, as specified here https://www.w3.org/TR/json-ld11/#example-71-language-map-expressing-a-property-in-three-languages. This approach is the one currently adopted in the European Digital Credentials scheme.

By my reading of the section 10.1, this approach seems to be supported, but the current language makes it a bit unclear if only examples described in the VC standard are supported, or whether any internationalisation approach supported by the JSON-LD standard is supported.

The suggestion would be to explicitly mention language-maps as a supported approach, and possibly include a language map as an example.

**Comment by msporny** [comment] 2024-04-21 14:06
> By my reading of the section 10.1, this approach seems to be supported, but the current language makes it a bit unclear if only examples described in the VC standard are supported, or whether any internationalisation approach supported by the JSON-LD standard is supported.

Language maps are supported. Any i18n mechanism supported by JSON-LD is supported by VCDM. 

That said, there were multiple organizations that objected to using advanced JSON-LD features. So, the best we could do in the specification is to try and find a middle ground. That resulted in this section:

https://w3c.github.io/vc-data-model/#type-specific-credential-processing

as well as the general section on JSON-LD usage:

https://w3c.github.io/vc-data-model/#json-ld

At present, I don't think we'll be able to get consensus to recommend language maps. They are already allowed per the specification, perhaps we can say more about them being allowed since you read the spec and it wasn't clear to you.

Given the above, what sort of language would you like to see in the specification?

**Comment by iherman** [comment] 2024-05-01 15:57
I believe the right pointer is https://w3c.github.io/vc-data-model/#language-and-base-direction and not what @msporny put into his comments

**Comment by iherman** [comment] 2024-05-01 16:10
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-05-01-vcwg#section3-3) on 2024-05-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Brent Zundel:** This was raised a couple of weeks ago -- consider explicitly allowing / recommending language maps.  
… This was read by someone outside the group who wanted more clarity on the i18n text -- they are making a concrete request for more text.  
… We did ask for specific language that they'd perhaps find acceptable -- would like to hear from folks on this in the group.  

**Anil John:** The ability to do language translations automatically for the credentials and attestations that we have would be good. I saw the feedback from Manu on the issue. Just a clarification question -- it sounds like basically having JSON-LD compact form, you have the ability to do that. Does anything in the current spec prevent the use of language maps in anyway shape or form?  
… For people who want to use that for translation?  

**Ivan Herman:** I think the problem is that there a section -- I don't know from the top of my head -- that shows how a pure JSON processor can handle JSON-LD credentials and that is not describing anything about language maps the way they are done in JSON-LD.  

**Anil John:** Understand Ivan's point -- I'm glad the flexibility exists that allows someone who wants to use a JSON-LD API to get functionality that is unique to JSON-LD and obviously in a context-specific processing love the flexibility to avoid doing that using static contexts and JSON schemas.  
… The question I would ask is -- if you wanted to use the features that are unique to JSON-LD, you would need to use a JSON processing capability. Great. If you choose to go down that path, does anything prevent you from doing that -- with the full understanding that you're going to be treating the credentials that way, you won't have access to that functionality?  

**Brent Zundel:** Nothing in the spec prevents you from using JSON-LD to use its full capabilities to my knowledge.  

> *Dmitri Zagidulin:* would just more examples (of multi-language VCs) help?

> *Benjamin Young:* This isn't about JSON-LD processing being required. The spec simply says "shape the JSON like JSON-LD does.".

> *Phil Feairheller:* Isn't the issue here simply that there isn't a comparable set of paragraphs that describe using JSON-LD specific language processing? Implication is that it would be good to have both explanations.

> *Anil John:* Thank you. that is very helpful dlongley.

**Gabe Cohen:** It seems there is a JSON-LD language map solution -- is there another one if they don't want to use it?  

**Brent Zundel:** Thanks Gabe.  

**Dmitri Zagidulin:** Reading this issue from Anthony, he does a lot of advising to the EU commission on the learning data model, etc. lots of skin in the game. The way he phrases the issue is that he would like it to clarify whether only the subset of i18n is supported or if multiple methods are supported.  
… JSON-LD has several methods, we support and recommend a subset, so I am reading the issue as "our subset vs. all options".  

**Brent Zundel:** Perhaps this issue could be resolved with a sentence that says "Additional JSON-LD capabilities could be utilized -- but if the recipient doesn't do JSON-LD processing they may not be received".  

**Dave Longley:** It's not a JSON-LD processing issue but a type-specific VC one.  

**Brent Zundel:** We'll get back on timing issues for the controller docs, thanks all!  
… Thanks for scribing, Dave.  

---

</details>

**Comment by iherman** [comment] 2024-05-29 16:12
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-05-29-vcwg#section5-2) on 2024-05-29

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.2. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Brent Zundel:** consider recommending language maps.  
… please jump on the queue.  

**Manu Sporny:** there's nothing preventing using them.  
… I don't think we can get to consensus on it.  
… we reached back out with that as a comment, but haven't heard back.  
… if we were to do that now, it'd be very last minute.  
… so the ask could be, please experiment.  
… especially since language maps differ from what we recommend right now.  
… and can reconsider it if/when we get feedback showing it's a good way for handling I18N.  

**Anil John:** mostly want to say that this is a feature of interest to DHS because of our international audience.  
… as long as there is not anything preventing us from using these capabilities from JSON-LD, then we are satisfied.  

**Ivan Herman:** should we show that JSON-LD can do this in an appendix?  

**Manu Sporny:** yes. we can do that in an appendix, and adding that would editorial.  

**Brent Zundel:** so, add an editorial example of language maps to the spec.  

> *Phillip Long:* +1 to editorial example to the language map spec.

**Brent Zundel:** manu has assigned himself, but someone else please volunteer.  

> *Dmitri Zagidulin:* I can volunteer.

**Brent Zundel:** thank you all for volunteering!  
… I'm unassigning manu.  
… and assigning dmitriz and Mahmoud.  
… o.k. we have time for one more topic.  
… let's jump to 1485.  

> *Dmitri Zagidulin:* clarifying question - language map examples should go into their own appendix? Or just in the internationalization section?

</details>

**Comment by iherman** [comment] 2024-06-12 16:06
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-12-vcwg#section3-3) on 2024-06-12

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




> *Phillip Long:* PL-ASU has joined #vcwg.

> *Dmitri Zagidulin:* (still workin' on it!) :).

**Brent Zundel:** next we have 1479 ... Consider explicitly allowing/recommending language maps for use in internationalisation. we had a conversation about this in May and then again later in May. Dmitri and Mahmoud are working on it. What's the status?  

**Dmitri Zagidulin:** currently working on an example at Digital Credentials Consortium. Should be done end of next week, if that's not too late.  

**Brent Zundel:** sounds good - look forward to seeing that.  

</details>

**Comment by iherman** [comment] 2024-06-19 17:33
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-19-vcwg#section2-1) on 2024-06-19

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Brent Zundel:** First one to look at today is 1479.  
… Dmitri, how is it going?  

**Dmitri Zagidulin:** No support required. Hope to have something by Friday.  

**Brent Zundel:** Next is 1462, it's closed, not discussing.  

</details>

**Comment by iherman** [comment] 2024-06-26 16:21
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-06-26-vcwg#section2-1) on 2024-06-26

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Dmitri Zagidulin:** coming along shortly.  

</details>

**Comment by iherman** [comment] 2024-07-03 16:06
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-03-vcwg#section1-2) on 2024-07-03

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Brent Zundel:** next we have language maps. do not see Dmitri on the call today. he is working on a PR but we have not seen movement for a month. if it's not happening we need to close it.  

**Manu Sporny:** I can take it.  

**Brent Zundel:** please reach out first to see his progress.  

</details>

**Comment by iherman** [comment] 2024-07-17 16:07
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section3-3) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.3. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Brent Zundel:** Dmitri, the time has come. We need a PR or we need to pull it. How are we doing?  
… Looks like we lost Dmitri.  

**Manu Sporny:** I'll raise a PR.  

</details>

**Comment by msporny** [comment] 2024-08-03 20:18
PR #1532 was merged to address this PR, closing.

**Closed by msporny** 2024-08-03 20:18 UTC
Labels: editorial, pr exists, CR1

**Comment by iherman** [comment] 2024-08-04 14:22
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-07-17-vcwg#section1-2) on 2024-07-17

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 1.2. Consider explicitly allowing/recommending language maps for use in internationalisation. (issue vc-data-model#1479)

_See github issue [vc-data-model#1479](https://github.com/w3c/vc-data-model/issues/1479)._




**Manu Sporny:** for next item, 1479, we need a language map example, Mahmoud raised a PR but the PR didn't have a language map.  
… is Dmitri in IRC?  
… Dmitri's contribution will take care of 1479, for next item Ivan has raised a PR.  

</details>
