### ISSUE TITLE
https://www.w3.org/2018/credentials cannot be found

### ISSUE THREAD

**Issue by vincentkelleher** [w3c/vc-data-model#1576] opened 2024-12-16 15:33 UTC
Hi 👋 

I'm going through the different contexts to find some information about attribut types and I noticed that https://www.w3.org/2018/credentials responds with a _404 File Not Found_ page.

![image](https://github.com/user-attachments/assets/05855d7b-dd03-4b4a-a0d5-c1abd195b3ad)

I'm not sure this is the best place to bring it up but I didn't find any other more adequate entrypoint.

**Comment by lemoustachiste** [comment] 2024-12-16 17:02
I'm not sure where you found this URL, but the context URLs for the VC spec are either:
- https://www.w3.org/2018/credentials/v1 for v1
- https://www.w3.org/ns/credentials/v2 for v2

**Comment by vincentkelleher** [comment] 2024-12-17 08:10
@lemoustachiste I found this URL by trying to follow the types referenced within the credential contexts you mentioned.

![image](https://github.com/user-attachments/assets/a2208c4c-a092-4f99-83b5-2430ff7d2e19)

My goal is to find the context describing `https://www.w3.org/2018/credentials#sriString`, I looked for it within the contexts above but couldn't find it so I tried to resolve https://www.w3.org/2018/credentials through my browser without success. I tried through Postman by adding the `Accept: application/ld+json` header just like a JSON-LD processor would without any success either.

My last attempt consisted in [following the URL on the WayBackMachine](https://web.archive.org/web/20240223191338/https://www.w3.org/2018/credentials/#sriString) which allowed me to find this:

![image](https://github.com/user-attachments/assets/3d242697-f171-48de-b259-ea37dc875941)

The issue is that the `https://www.w3.org/2018/credentials#sriString` type should be defined in `https://www.w3.org/ns/credentials/v2` according to the previous documentation and as the URL doesn't provide new documentation I just cannot find the description I'm looking for.

**Comment by msporny** [comment] 2024-12-17 16:23
Thanks for the bug report. The issue has been fixed. 

The root cause was a failed build of the vocabulary (due to mismatched versions between node.js 18 and yml2vocab v1.4.5+). The failed build caused the file to stop existing, which is re-directed to from the W3C website.

I have confirmed that the link now works again, for example:

https://www.w3.org/2018/credentials#sriString

Closing as fixed.

**Closed** 2024-12-17 16:23 UTC
Labels: editorial, CR1

**Comment by vincentkelleher** [comment] 2024-12-17 16:55
Thanks @msporny I can now follow the link 👍 

Although I can't find a type corresponding to `sriString` in any context, is that normal ?

**Comment by vincentkelleher** [comment] 2024-12-17 21:57
@msporny I did express myself correctly 🤦 

Sorry I meant the context where I can find something like :

```json
// ...
   "sriString": {
      "@type": "xsd:string"
    },
// ...
```

Maybe I'm getting something wrong ?

**Comment by msporny** [comment] 2024-12-17 22:40
`sriString` is a data type and is used here (in that file I linked to above):

```
    "digestSRI": {
      "@id": "https://www.w3.org/2018/credentials#digestSRI",
      "@type": "https://www.w3.org/2018/credentials#sriString"
    },
```

Note the following line:

>  ```"@type": "https://www.w3.org/2018/credentials#sriString"```

it ends in `sriString` -- because that's the datatype for `digestSRI` values. Did that answer your question?

**Comment by vincentkelleher** [comment] 2024-12-19 10:43
Thank you @msporny, I just found what I was looking for with a `curl` command:

```bash
curl --location 'https://www.w3.org/2018/credentials' --header 'Accept: application/ld+json'
```

![image](https://github.com/user-attachments/assets/4bbfa15f-85ac-436f-b39b-d09dd7a84298)

That is the machine readable content I needed ✨
