### ISSUE TITLE
clarify what an "appropriate VC/VP" is

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-data-model#848] opened 2021-12-06 18:39 UTC
[Section 4.3 Types](https://www.w3.org/TR/vc-data-model/#types) states that type information is used "to determine whether or not a provided verifiable credential or verifiable presentation is appropriate."

Could you please clarify concrete elements that constitute "appropriate VC/VP" and how they can be verified? I imagine certain claim sets, crypto suites, etc. would make a VC/VP "appropriate" for it to be used in a certain framework, context, ecosystem, etc.?

**Comment by David-Chadwick** [comment] 2021-12-08 16:51
I suggest appending to the text to say "to determine whether or not a provided verifiable credential or verifiable presentation is appropriate for the application use case"

**Comment by iherman** [comment] 2021-12-08 17:13
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-08-vcwg#section3-1) on 2021-12-08

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. clarify what an "appropriate VC/VP" is (issue vc-data-model#848)

_See github issue [vc-data-model#848](https://github.com/w3c/vc-data-model/issues/848)._




**Brent Zundel:** Clarify what an appropriate VC/VP is. The type information is used to determine if a provided VC/VP is appropriate. The issue is looking for clarification on what appropriate means..  

**Manu Sporny:** Should be 1.1 editorial..  

**Dave Longley:** +1 to editorial 1.1.  

**Brent Zundel:** Does anyone in the group want to have themselves assigned to do a PR to add text?.  

**David Chadwick:** I'll do it..  

**Charles Lehner:** Thanks, I was just wondering regarding about PRs #829 / #751 ... I'm wondering how to hear back..  

**Manu Sporny:** We will ping the person and ask if our merge addressed their concern..  

**Charles Lehner:** Ok..  

</details>

**Comment by msporny** [comment] 2022-12-14 18:11
I'll apply the suggestion from @David-Chadwick in an upcoming PR.

**Comment by msporny** [comment] 2023-01-07 19:42
PR #1005 has been raised to address this issue. This issue will be closed once that PR is merged.

**Comment by brentzundel** [comment] 2023-01-24 22:01
PR #1005 has been merged, closing

**Closed by brentzundel** 2023-01-24 22:01 UTC
Labels: editorial, pr exists
