### ISSUE TITLE
Add canonical way to reference JSON Schema against which credential should be validated

### ISSUE THREAD

**Issue by Drabiv** [w3c/vc-data-model#129] opened 2018-03-14 15:26 UTC
I think it would be beneficial to have in the spec a description on how to reference  JSON Schema against which credential should be validated. This reference should be of course optional.

**Comment by msporny** [comment] 2018-07-17 15:39
This is a duplicate of #128.

**Comment by msporny** [comment] 2018-10-22 21:08
We discussed this at W3C TPAC, agree that it would be a useful feature, but we are out of time to develop a solution for this. We do have an idea that would look something like this:

Create a `schemaVerification` property that links to an object. The object contains various different ways to verify a schema, including JSON Schema, SHEX, JSON-LD Frame, etc.

This should be deferred to a future version of JSON-LD.

**Comment by brentzundel** [comment] 2019-03-04 15:09
Decision at Barcelona F2F: This is solved by credential schema, close.

**Closed** 2019-03-04 15:38 UTC
Labels: ImplementationGuidance, W3C TPAC 2018
