### ISSUE TITLE
Does pseudo-anonymity require the issuer to cooperate?

### ISSUE THREAD

**Issue by stonematt** [w3c/vc-data-model#209] opened 2018-07-27 17:04 UTC
This question came up in our use cases call in issue https://github.com/w3c/vc-use-cases/issues/10

How explicit should we be in the DM about issuer’s role in creating ZKP credentials for things like withholding “name” as discussed in the use cases section 3.5. 
https://w3c.github.io/vc-use-cases/#professional-credentials -- see the Paula example in item C.5 Social authority.

in other words, can I say “I’m in control of credential X in which I’m the subject, but you can’t know who I really am”

**Comment by stevenrowat** [comment] 2018-07-30 18:52
I'm uncertain exactly what is being suggested here. Perhaps an example will help?

Suppose I want to publish a story about Country X, of which I'm a citizen, and state in the story that I'm a citizen, backed up by a VC corroborating this, but also use a pseudonym to avoid dangerous repercussions on me and my family.

But the problem is that Country X is the place that would issue my VC stating that I'm a citizen, and would be the issuer, and would be required to back up the VC at the DID  level. So the question is:
Do they have to agree that I can publish pseudonymously? Or is there a way that I can do it anyway, using Zero Knowledge Proofs, and even the government of Country X won't know who they've corroborated in the VC? 

Is that what you're asking?

If so, interesting question, and I don't know the answer, but I hope somebody does.

**Comment by jandrieu** [comment] 2018-07-30 20:37
It will be relatively trivial for an issuer to construct even ZKP proofs that support third party correlation, even accidentally. For instance, you can have a ZKP that proves your driver's license # without revealing date of birth or address. It's a fine use of ZKP if you care about rental companies getting unnecessary PII, but it doesn't do anything to help with correlating you across rental establishments via your driver's license #.

To make things worse, even with good, well-intentioned data modeling practices, there are often plenty of ways to de-anonymize ZKP credentials. Consider it a corollary of the law of unintended consequences. You only have to mess up once for links to be made.

The best anti-censorship techniques mean not only diligent data modeling (which is under the issuer's control) but also judicious use of those credentials and affiliated data and meta-data. Ultimately, it's an economic question of how much trouble it is worth it to support a certain level of anonymity (both for holders and issuers) versus the economic cost and value for third-parties wishing to de-anonymize. If you're the target of a billion dollar manhunt (think Osama Bin Laden), then ZKP VCs are only a small part of your challenge. If you want to pseudonymously post to Post Secret about childhood trauma and want a ZKP proving you were on the Valley High School soccer team in 2018, the economics are substantially different.

**Comment by stevenrowat** [comment] 2018-08-07 17:12
> I think the answer to this is yes - the issuer will issue a VC that supports ZKP. The holder will not have the authority or capability to decompose and share discreet attributes of a claim unless the issuer enables that.

Does this mean that a holder can't use their citizenship in Nation X pseudonymously unless Nation X has previously deemed ZKPs OK? Similarly, in the case of the State Medical Board example, Doctor X can't claim membership in the Medical Board via a VC, yet make a pseudonymous statement, unless the State Medical Board has previously OK's such ZKP VCs?  And so on, for all issuers?

This may be the best solution available, but it does seem to make it difficult on whistleblowers in particular.

OTOH, I can see that many issuers will refuse to issue a VC at all if they think it might be used pseudonymously. Seems like a thorny problem.

**Comment by TzviyaSiegman** [comment] 2018-08-10 19:01
This is related to a concern I have about section [10.8 Principle of Minimum Disclosure](https://w3c.github.io/vc-data-model/#the-principle-of-minimum-disclosure). I believe that it is easy to misunderstand the DM with the misconception that minimum disclosure is the default and/or controllable by the subject. I think it would be a good idea to spell out more explicitly what steps need to be taken (e.g. ZKP, hashing hashed credentials) to make mimimum disclosure possible.

**Comment by ChristopherA** [comment] 2018-08-10 19:48
@TzviyaSiegman > I think it would be a good idea to spell out more explicitly what steps need to be taken

+1

I think there are a number of interesting scenarios here around Minimum Disclosure, that are completely separate from cryptographic selective disclosure/attribute blinding/zkp and anti-correlation capabilities, and should be.

You note "the misconception that minimum disclosure is the default and/or controllable by the subject" — I've run into this too. The subject who is also holding the claim should be able to minimize sending it in some way, both automated under some type of algorithm or interactive protocol, but and also under direct user control. If you are a holder /= subject, you should be held to a high standard. And there are things that issuers can/should/must do as well to help subjects and holders to be able to minimize their disclosure.

**Comment by kdenhartog** [comment] 2021-06-14 15:47
This was discussed in the maintenance working group. @brentzundel believes he can write up a PR to address this one.

**Comment by iherman** [comment] 2021-06-15 07:07
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-06-14-vcwg#section3-5) on 2021-06-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.5. Does pseudo-anonymity require the issuer to cooperate 

_See github issue [#209](https://github.com/w3c/vc-data-model/issues/209)._




> *Gerhard Oosthuizen:* Hi everyone. Unfortunately have to drop off. Nice meeting you. Will do some pre-reading of issues before our next session to be able to contribute more.

> *Kyle Den Hartog:* +1 to that Brent

> *Manu Sporny:* Agree with that text that brent just said

**Brent Zundel:** it would be appropriate to add text to the Zero Knowledge proofs section  

**David Chadwick:** maybe the scope of this issue is larger, to what extent can an issuer control the discloser a holder has  

**Brent Zundel:** assign brent to the issue, an idea of how to move forward with it  

**Manu Sporny:** agreed with the original text - but consider one use case: witness issuers  

> *Manu Sporny:* +1 to giving brent a shot at the text :)

**Gregory Natran:** in response to DavidC, caution to preventing users from disclosing, the information is theirs and there may be consequent issues with restrictions on the holder/subject  

**Brent Zundel:** to throw conversation into a new PR and can continue the discussion  
… anything that is not "deferv2" or "erratum" - please add a comment to the issue to describe what you feel the proper classification *should* be  

</details>

**Comment by iherman** [comment] 2021-10-07 08:51
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-10-06-vcwg#section3-1) on 2021-10-06

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 3.1. Does pseudo-anonymity require the issuer to cooperate? (issue vc-data-model#209)

_See github issue [vc-data-model#209](https://github.com/w3c/vc-data-model/issues/209)._




**Brent Zundel:** I vaguely remember this conversation... several years ago. We talked about it a few months ago  
… At the time I was confident I could write a PR to address this, but now reviewing it I no longer recall...  

**Kyle Den Hartog:** ... We left it more vague... questions about pseudonymity... a cover clause to abstract around ZKPs...  
… that the issuer must give you something you can derive from  

**Dave Longley:** I think that is good and helpful... Letting people reading the spec know that if the issuer is not cooperating to do this, then you don't get it.  
… The issuer has to offer you this feature, and not try to backdoor recreate correlation or collision  
… The notion is that there is some trust in the issuer to cooperate in this scheme for it to work.  

> *Kyle Den Hartog:* This is the statement in the spec, that I think generally covers this: "The verifiable credential MUST contain a Proof, using the proof property, so that the holder can derive a verifiable presentation that reveals only the information than the holder intends to reveal."

**Dave Longley:** I think this should be stated in the spec  

**Ted Thibodeau Jr.:** I recall the issue was about active participation by the issuer, rather than about making a derived credential of a credential one has in their hand  

**Dave Longley:** One attack: even if the issuer is following these protocols... if the issuer is creating a different public key for every user they issue a credential to, they re-introduce a way to correlate and track users.  
… Issuer should opt in, and must also decide not to track you  

**Kyle Den Hartog:** I see that, think it could be added to the privacy section, not tie specifically to ZKPs only  
… There are other ways an issuer could create pseudonymity... active issuer policies  

> *Dave Longley:* thanks brent

> *Ted Thibodeau Jr.:* +1 kdenhartog's described editorial addition, whether done by kdenhartog or brent

**Brent Zundel:** I'll put a PR in, and we'll see if it's acceptable  

</details>

**Comment by iherman** [comment] 2021-11-10 17:25
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-11-10-vcwg#section5-1) on 2021-11-10

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 5.1. Does pseudo-anonymity require the issuer to cooperate? (issue vc-data-model#209)

_See github issue [vc-data-model#209](https://github.com/w3c/vc-data-model/issues/209)._




> *Brent Zundel:* related to PR #830.

_See github pull request [vc-data-model#830](https://github.com/w3c/vc-data-model/pull/830)._




**Brent Zundel:** pr exists for this issue so it will automatically close when pr is merged.  

</details>

**Comment by iherman** [comment] 2021-12-02 09:50
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2021-12-01-vcwg#section4-5) on 2021-12-01

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 4.5. Does pseudo-anonymity require the issuer to cooperate? (issue vc-data-model#209)

_See github issue [vc-data-model#209](https://github.com/w3c/vc-data-model/issues/209)._




_See github pull request [vc-data-model#830](https://github.com/w3c/vc-data-model/pull/830)._




**Brent Zundel:** I raised a PR to address this, got some feedback, that PR has existed for 21 days, but not labeled properly -- waiting for PR to formally be accepted..  
… Last thing I think Ted made, requested some changes, accepted your suggestions -- re-review would be good..  

**Ted Thibodeau Jr.:** I'll look at that..  

</details>

**Closed** 2021-12-04 18:51 UTC
Labels: PR exists, ZKP, Errata, v1.1 (editorial)
