### ISSUE TITLE
Problems with the Extensibility Section

### ISSUE THREAD

**Issue by David-Chadwick** [w3c/vc-data-model#190] opened 2018-06-24 23:22 UTC
The extensibility section appears to only allow extensibility if JSON-LD is used, whereas VCs should be infinitely extensible if pure JSON is used as well. 
Extensibility can easily to added to VCs irrespective of whether JSON-LD or pure JSON is used to encode the VC by the use of strong typing i.e. each VC should contain sufficient type information, either as a property of the VC itself, or of its embedded objects, so that the verifier can know definitely what properties must be in the VC, what properties may be in the VC, and what properties must not be in the VC.

**Comment by msporny** [comment] 2018-06-26 14:28
Let's presume that we don't have JSON-LD. What are the rules for providing infinite extensibility when using pure JSON? What are the processing rules? How does one write code to enforce those processing rules?

I posit that you will just end up re-inventing JSON-LD.

I've suggested a path forward here: https://github.com/w3c/vc-data-model/issues/183#issuecomment-400323137

One of these issues is a duplicate of the other. Please close one of these issues so we can focus the discussion in a single issue.

**Comment by David-Chadwick** [comment] 2018-06-30 15:50
I have answered your above questions more generally in #183, but to summarise here:
i) infinite extensibility is provided by the addition of new unique type URIs. Any issuer can add any new types it wants to.
ii) the processing rules for a verifier are at their simplest, if you dont understand a type, you reject the VC. (You might additionally notify the administrator to update the implementation config parameters to understand the new types if the verifier wants to)
iii) it is not necessary, and indeed it can be dangerous in a security context, to have the verifier's software import new types and configure how to process them automatically, because I am assuming that the semantics of these cannot be determined by JSON-LD syntax alone.

**Comment by msporny** [comment] 2018-07-03 14:34
> i) infinite extensibility is provided by the addition of new unique type URIs. Any issuer can add any new types it wants to.

-1, this will lead to an unnecessary bifurcation between the JSON and JSON-LD markup. This point is further elaborated upon in this comment: 

https://github.com/w3c/vc-data-model/issues/183#issuecomment-402177111

> ii) the processing rules for a verifier are at their simplest, if you dont understand a type, you reject the VC. (You might additionally notify the administrator to update the implementation config parameters to understand the new types if the verifier wants to)

+1, we can make this happen for both JSON and JSON-LD.

> iii) it is not necessary, and indeed it can be dangerous in a security context, to have the verifier's software import new types and configure how to process them automatically, because I am assuming that the semantics of these cannot be determined by JSON-LD syntax alone.

I don't think anyone is proposing that we do this, so it's a red herring.

**Comment by msporny** [comment] 2018-07-08 20:07
PR submitted to address this issue: https://github.com/w3c/vc-data-model/pull/196

**Comment by msporny** [comment] 2018-07-19 15:45
Closing, as I believe we've addressed this issue in PR #196. Re-open if we haven't.

**Closed** 2018-07-19 15:45 UTC
Labels: Type-Discussion
