### ISSUE TITLE
4.3 Types

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#484] opened 2019-03-27 08:17 UTC
"The type system for the Verifiable Credentials Data Model is the same as for [JSON-LD] and is detailed in Section 5.4: Specifying the Type and Section 8: JSON-LD Grammar" 

Should not be forced into JSON-LD as the type data model, this should allow for JSON models such as JWT/CWT. There are many parsers and verifiers out there today for JWT/JWS

**Comment by brentzundel** [comment] 2019-03-27 18:28
It was explained to me that selecting the type system for the Verifiable Credentials Data Model to be the same as the type system for JSON-LD, feed the Verifiable Credentials Data Model from needing to specify its own type system.
It is my understanding that using the JSON-LD type system for this data model does not force any implementor to use JSON-LD, but that JWT/JWS are fully compatible with the type system specified.
@msporny or @dlongley may have more detail to share in addressing this issue.

**Comment by msporny** [comment] 2019-03-30 01:10
> Should not be forced into JSON-LD as the type data model, this should allow for JSON models such as JWT/CWT. There are many parsers and verifiers out there today for JWT/JWS

Can you please be concrete in the problem that you think this creates? What specific technical issue are you concerned about and what specific and concrete technical solution are you proposing?

**Comment by nadalin** [comment] 2019-04-01 11:09
@msporny I'm very concerned about the use of JSON-LD and how proof mechanisms would work, I know how they will work with JWT as this is proven work, the lack of a completed signature and C14N specification is a show stopper. So I'm proposing a step back and being able to represent a VC as a JWT and use the JWS/E as proof mechanisms for this

**Comment by brentzundel** [comment] 2019-04-01 13:00
Unless you can also demonstrate how to do zero-knowledge proofs and
selective disclosure with JWTs and JWEs, what you are proposing is a
non-starter.
The data model we have produced is compatible with many proof mechanisms.
This means it is useful in a wide variety of use cases.

The things you wish to use it for, and the formats you dish to support, are
not prohibited by the data model.
Limiting the data model to your particular formats and proof mechanisms
would prohibit a number of other valuable use cases and cause the data
model to be unusable by many.

What is not clear to me is why these suggestions are coming at this point.
We have published drafts of our work for a long time. If you had issues
with JSON-LD being one possible means of representing the data model you
should have spoken up months ago.

What I still have not heard clearly expressed is why, in your opinion,
verifiable credentials would be better if they were so limited in the scope
of problems they might address.
Why, in addition to demanding that the data model support your preferred
formats (which it already does), do you insist on trying to change the data
model so that it prohibits the formats required by the use cases of others?

**Comment by nadalin** [comment] 2019-04-01 13:34
@brentzundel Comments can come in at anytime, especially when you transition. 

You have to demonstrate that you can actually do the normative things that have been described in the text in an interoperable way. I don't see how that can be done, there is no proposed interoperable way to do zero-knowledge proofs since no mechanism was defined.

**Comment by brentzundel** [comment] 2019-04-01 13:40
You have not addressed my questions and I would appreciate very much if you
could do so.

**Comment by nadalin** [comment] 2019-04-01 13:46
@brentzundel There is only one question in your text which is "Why, in addition to demanding that the data model support your preferred
formats (which it already does), do you insist on trying to change the data
model so that it prohibits the formats required by the use cases of others?"

Because there is no proof mechanisms that are documented beyond JWS/E for for JWT as this is the only interoperable means of proofing since there is no JSON-LD proof specification

**Comment by nadalin** [comment] 2019-04-01 13:49
@brentzundel I have no objection to the JSON-LD model but to mandate that when there is no proofing mechanism is very odd, keep it simple and work with JWTs and if it works with JSON-LD that would also be good

**Comment by brentzundel** [comment] 2019-04-01 14:02
That's good to hear. The data model has examples of how it can be used with
JWTs, and JSON-LD. There are also JSON-LD examples with both JSON-LD
signatures and CL- signatures.
Sounds like we've got our bases covered.

Where we may still disagree is in the need for the proof mechanisms that
are used with the verifiable credentials data model to also be part of some
standard specification. Is that an assertion you are making?

**Comment by nadalin** [comment] 2019-04-01 14:19
@brentzundel I don't think I would say we are quite there yet. Looking for a simple data model that supports JSON JWT as VC and the use of JSON-LD as VC for those more complicated needs

**Comment by David-Chadwick** [comment] 2019-04-01 14:35
One mandatory requirement for the simple data model is support for extensibility. The existing type mechanism does that (and this was the original topic of this issue, not proof mechanisms) in a way that is not dependent upon JSON-LD.

**Comment by brentzundel** [comment] 2019-04-01 14:42
My apologies for not fully understanding.

Your second sentence is either missing the subject, or is itself the
subject and is missing the preposition.

My intention with that statement is not to criticize your grammar, but to
let you know that I don't want to put words in your mouth and possibly
assume a meaning you didn't intend.

I think we may be getting closer to a point of common understanding and I
don't want to jeopardize that by interpreting your statements incorrectly.

**Comment by brentzundel** [comment] 2019-04-01 23:21
@nadalin This issue was raised to bring up the following points:
1. "Should not be forced into JSON-LD as the type data model"
2. "should allow for JSON models such as JWT/CWT."

These points were addressed:
1. "using the JSON-LD type system for this data model does not force any implementor to use JSON-LD"
2. "JWT/JWS are fully compatible with the type system specified"

You then add: " I'm very concerned about the use of JSON-LD and how proof mechanisms would work"
While this is certainly a valid concern (as it stimulated quite a conversation here), @David-Chadwick was correct when he pointed out: "The existing type mechanism does that (and this was the original topic of this issue, not proof mechanisms) in a way that is not dependent upon JSON-LD."
@nadalin If you would like to continue conversation around proof mechanisms, perhaps Issues #486, #487, #489, or #490 may be better.

If there are points related to this issue that you feel have not been addressed, please let us know.

**Comment by msporny** [comment] 2019-04-03 00:46
@nadalin wrote:
> I'm very concerned about the use of JSON-LD and how proof mechanisms would work

Since the title of the issue is "4.3 Types" and your original issue was about the type system, and as @brentzundel has stated, there are other issues you have raised about Proofs, then I'm going to try and focus on the original issue you raised (and follow up on the proofs stuff in the other issues you raised that are specific to proofs).

@nadalin wrote:
> Should not be forced into JSON-LD as the type data model

The JSON-LD type model (coupled with Section 4.2) basically states that you use `type` to express the type and you use URLs (or anything that maps to a URL) as the value(s). 

Can you explain, in concrete terms (or via an example), the specific issue you are concerned about. How would a JSON-based Verifiable Credentials processor be forced to use a JSON-LD library in this case?

> this should allow for JSON models such as JWT/CWT. 

The specification allows for JSON, JWTs, and CWTs. Can you explain, in concrete terms, how the use of JSON, JWT, or CTWs are prevented? What could you do before that this section specifically prohibits?

> There are many parsers and verifiers out there today for JWT/JWS

Yes, that is true, and the specification acknowledges that and supports embedding of VCs in JWTs, secured by JWS. Can you explain, in concrete terms (using an example), how the use of JWS/JWT would be prevented?

**Comment by nadalin** [comment] 2019-04-03 06:22
The JWT parsers out there that I know about can't parse the JSON-LD types, thus a JWT "vc" would be restricted to JSON types, as long as this restriction is made I see no issues, but that is not the restriction today in the specification.

**Comment by dlongley** [comment] 2019-04-03 14:05
@nadalin,

> The JWT parsers out there that I know about can't parse the JSON-LD types, as long as this restriction is made I see no issues, but that is not the restriction today in the specification.

Could you please give a very specific, concrete, JWT example of where a problem would occur that your suggestion would address? Without being able to see such an example, it does not seem to many in the group that there is a problem. We'd be interested in exploring ways to help to resolve a problem but we first need to understand it through a concrete example.

**Comment by nadalin** [comment] 2019-04-03 16:51
A JWT parser would expect this as a claim:

{"Address":"Microsoft Way",
      "postalCode":"98052"}

And not this:

"address": {

        "@type": "PostalAddress",

        "addressLocality": "Colorado Springs",

        "addressRegion": "CO",

        "postalCode": "80840",

        "streetAddress": "100 Main Street"

      },

**Comment by David-Chadwick** [comment] 2019-04-03 17:15
We have an example of address in "Example 36 A credential uniquely identifying a subject" and it is not like the above. Furthermore we are using schema.org properties.

**Comment by nadalin** [comment] 2019-04-03 18:22
@David-Chadwick JWT Parser would not understand that same issues as I my example

**Comment by dlongley** [comment] 2019-04-03 19:06
I put this into [jwt.io](https://jwt.io) :

```js
{
  "sub": "did:example:ebfeb1f712ebc6f1c276e12ec21",
  "jti": "http://example.edu/credentials/3732",
  "iss": "did:example:abfe13f712120431c276e12ecab",
  "iat": "1541493724",
  "exp": "1573029723",
  "nonce": "660!6345FSer",
  "vc": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": ["VerifiableCredential", "AddressCredential"],
    "credentialSubject": {
      "type": "PostalAddress",
      "addressLocality": "Colorado Springs",
      "addressRegion": "CO",
      "postalCode": "80840",
      "streetAddress": "100 Main Street"
    }
  }
}
```

It successfully produced this JWT:

```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXhhbXBsZTplYmZlYjFmNzEyZWJjNmYxYzI3NmUxMmVjMjEiLCJqdGkiOiJodHRwOi8vZXhhbXBsZS5lZHUvY3JlZGVudGlhbHMvMzczMiIsImlzcyI6ImRpZDpleGFtcGxlOmFiZmUxM2Y3MTIxMjA0MzFjMjc2ZTEyZWNhYiIsImlhdCI6IjE1NDE0OTM3MjQiLCJleHAiOiIxNTczMDI5NzIzIiwibm9uY2UiOiI2NjAhNjM0NUZTZXIiLCJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL2V4YW1wbGVzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJBZGRyZXNzQ3JlZGVudGlhbCJdLCJjcmVkZW50aWFsU3ViamVjdCI6eyJ0eXBlIjoiUG9zdGFsQWRkcmVzcyIsImFkZHJlc3NMb2NhbGl0eSI6IkNvbG9yYWRvIFNwcmluZ3MiLCJhZGRyZXNzUmVnaW9uIjoiQ08iLCJwb3N0YWxDb2RlIjoiODA4NDAiLCJzdHJlZXRBZGRyZXNzIjoiMTAwIE1haW4gU3RyZWV0In19fQ.MJ5BuMjsVz4skNtUWtHd-oRF7kAAYQMhO61fAQ2sCY0
```

The HMAC secret used was `test`. There did not appear to be any problems.

cc: @awoie, do you think there are any problems here? I'm under the impression that JWT parsers would not break on a "vc" JWT claim and the above parser certainly works.

**Comment by nadalin** [comment] 2019-04-03 19:30
@dlongley its ignoring the "vc" as it does not understand, my point is that a JWT should be able to understand and process a "vc" but there are restrictions on the what a "vc" would look like

**Comment by nadalin** [comment] 2019-04-03 19:34
@dlongley the JWT claim data model should also be allowed data model for "vc"

**Comment by dlongley** [comment] 2019-04-03 20:57
@nadalin,

> my point is that a JWT should be able to understand and process a "vc" but there are restrictions on the what a "vc" would look like

Is this the same issue as #520, where we've stated that the group expects that "vc" will be registered as an IANA claim? If so, can we close this one as a duplicate?

If not, can you explain what parsing issues you're concerned about? Providing some minimal, runnable code that demonstrates the issue would help the group understand the best. The data model spec provides encoding and decoding rules for the "vc" claim in the [JWT and JWS Considerations](https://w3c.github.io/vc-data-model/#jwt-and-jws-considerations) section.

> the JWT claim data model should also be allowed data model for "vc"

There are two ways that the JWT claim data model can be used with a JWT. The first way is by far the simplest, which is to simply use it like you do today with JWTs. You can always include other JWT claims along side the "vc" claim. This allows the same centralized extensibility model (of updating the IANA registry) to be reused as it is today, without any changes.

The second way is to use the decentralized extensiblity model provided by the VC data model and `@context`. You can create an `@context` that defines the mappings from whatever set of JWT claims you wish to use and include that in the `@context` array in the "vc" Verifiable Credential JSON. Then you can use those defined JWT claims within "vc" itself.

Both of these mechanisms can be used today without any changes to the VC data model spec.

**Comment by nadalin** [comment] 2019-04-04 07:45
@dlongley There are thousands of sites using the JWT claim data model, the "vc" data model should alternatively allow claims to be defined per the JWT data model for claims. So this way the "vc" claim could be processed by the JWT processors in full. I understand there will still be a need for more complex claims and thus then need for the JSON-LD model but lets make it easy for the simple cases and allow the existing JWT claims and the claims defined in the IANA registry to be used ASIS

**Comment by dlongley** [comment] 2019-04-04 14:23
@nadalin,

> There are thousands of sites using the JWT claim data model, the "vc" data model should alternatively allow claims to be defined per the JWT data model for claims. So this way the "vc" claim could be processed by the JWT processors in full. I understand there will still be a need for more complex claims and thus then need for the JSON-LD model but lets make it easy for the simple cases and allow the existing JWT claims and the claims defined in the IANA registry to be used ASIS.

My response above covered two ways to do this. For JWT users, they can use decentralized extensibility and/or more complex claims by putting them into a VC underneath the "vc" JWT claim in conjunction with the existing JWT claims model without any changes. If users would like to use the JWT data model inside of a VC or with an alternative proof mechanism, they may use the decentralized extensibility and interoperability mechanism "`@context`" to put those claims into a VC. I believe the spec enables this today.

**Comment by nadalin** [comment] 2019-04-04 14:34
@dlongley I don't think this will work without changes to specification

1. No JSON-LD statements would be allowed
2. No @context allowed
3. Document JWT claims allowed
4. JWS/E stated as proof mechanisms
5. and I'm sure there will be other things that need to be documented to allow a JWT to be claim

**Comment by stonematt** [comment] 2019-04-30 14:30
RESOLVED: The WG believes that the type system described in the specification does not require a JSON-LD processor to be used and the concerns raised in issue #484 have been demonstrated to be expressible in JWTs using the VC Data Model in a way that is both conformant with JWTs as well as other expression mechanisms. No technical examples have been provided that demonstrate that the type system used for the Verifiable Credentials Data Model either 1) requires a
8:30 AM JSON-LD processor to process, or 2) causes any known JWT library to fail to process a JWT containing type information (or any other known markup used in the Verifiable Credentials specification). No changes should be made to the specification.

**Comment by stonematt** [comment] 2019-04-30 14:32
From VCWG call on April 30, 2019: 
RESOLUTION: The WG has considered the proposals raised in Issue #484 and continues to support both JWTs and JSON-LD in the specification, continues to support the use of @context as it exists in the specification today, supports any valid JWT claim expressed in a JWT-based serialization, and supports the use of JWS with the specification. The WG has discovered no technical reason that JWE cannot also be used to encrypt data expressed in the specification. Issue
8:32 AM #484 should be closed with no changes to the specification.

**Comment by burnburn** [comment] 2019-05-17 18:55
The outstanding request by @nadalin to mandate support by all implementations of the JWT format will be tracked by issue #634.  Closing.

**Closed by burnburn** 2019-05-17 18:55 UTC
Labels: Pending 7 Day Close
