### ISSUE TITLE
Various questions related to the use of the "type" property

### ISSUE THREAD

**Issue by vieillevigne** [w3c/vc-data-model#174] opened 2018-05-10 21:14 UTC
I am trying to figure out the normative use of the property, “type”. From the draft of May 8 I observe the following:
 
- Every object at the top level (except for @context and verifiable profiles) has a “type” property
- Every subobject, except for subobjects which are the values of “claim” properties, have “type”properties.
- Apart from its occurrence in sections 7.2, 8.1 and 8.2 ‘type’ only appears in examples. The sections just mentioned also contain the only apparently normative occurrences of ‘type’.
- The identifier “Credential” appears on the right-hand side of a “type” property only in ‘[..]’.
- With two exceptions “Credential” always appears with another identifier containing ‘Credential’.
- The only occurrences of a multiplicity of types embraced by ‘[..]’ (presumably denoting lists not sets) lead with “Credential”.
- The type to the right of “Credential” always seems to be a specialization (subtype ?) of “Credential”.
- “Credential”, “DocumentVerfification” and “VerfiableProfile” occur in singleton lists.

My questions follow:
 
1. Except for the fact that the object values associated with “claim” properties do not themselves have “type”  properties, I’d really like to be able to say that “every object and subobject MUST have a “type”  property”. Why don’t, for example, the apparent claim objects have “type” properties?
2. I’d like to be able to say that lists of types denote increasing specialization of type. Why then are there singleton occurrences of types in lists – especially when there are lots of singleton occurrences of types not in lists? What use can I make of a type specifically called out in a specialization hierarchy (if that is what a list intends)? In the case of types not used in lists, how do I know that they are not parts of specialization hierarchies elsewhere? Indeed, how do I know that “Credential” does not appear in a specialization hierarchy? Under what circumstance does one use a list for a singleton?
3. I am particularly puzzled by the assertion at section 5.2 that “A credential MAY be made verifiable by adding the following property …”. This suggests that a credential may be made verifiable in some other way than providing a proof. It also suggests that a credential need not be verifiable at all. Moreover, the example which immediately follows does have a “proof” property and also has a “ProofOfAgeCredential” type. Why is the latter needed in the presence of the former? What are sufficient conditions to be a verifiable credential? What are necessary conditions to be a verifiable credential? Is it intended that there be credentials which are not verifiable?
4. While section 7.2 apparently does say that an object of the “Credential” type MUST have “type” and “claim” properties, it (surprisingly) does not appear to say such a thing for “issuer” and “issued”. The meaning of a type is ordinarily understood to derive from its relationships with other types. On that account, it seems unlikely to me that something intended to be a “Credential” does not always have “issuer” and “issued” values. So what properties MUST an object of type “Credential” have?
5. A verifiable profile object appears to have no requirement at all on its properties. While EXAMPLE 18, EXAMPLE 22 – apparently verifiable profile objects -- have no  “type”  property, EXAMPLE 5 does. (BTW, the ‘Section’ reference in section 8.2.2 is invisible and it actually points to the top level of the document. Ditto the ‘Section’ reference in 8.2.1.) Is the absence of a “type” an error?
6. “type” appears to be a reserved word in JSON schema. I can imagine some of the parties interested in verifiable claims might also be interested in making use of JSON schema to (partially) specify claims. While the magic of namespaces can allow one to deconflict, might not another keyword be better?

**Comment by msporny** [comment] 2018-05-19 17:51
I'm going to respond to your observations first:

> Every object at the top level (except for @context and verifiable profiles) has a “type” property

This is typical of most JSON-LD documents. There are cases where type may be missing (where you're throwing some ad-hoc thing together and you don't have type information for it. RDF (in general) provides for reasoning about the types of objects based on their properties (duck typing).

> Every subobject, except for subobjects which are the values of “claim” properties, have “type”properties.

Yes, usually, but not always (as explained above).

> Apart from its occurrence in sections 7.2, 8.1 and 8.2 ‘type’ only appears in examples. The sections just mentioned also contain the only apparently normative occurrences of ‘type’.

Yes, that's because the group hasn't made up its mind yet on whether or not type is required. There are good arguments for and against.

> The identifier “Credential” appears on the right-hand side of a “type” property only in ‘[..]’.

Yes, because we're trying to express that objects can have multiple types. For example, you can be a "Child" and a "Parent" at the same time.

> With two exceptions “Credential” always appears with another identifier containing ‘Credential’.

Yes, but that may not always be the case (per the first point above).

> The only occurrences of a multiplicity of types embraced by ‘[..]’ (presumably denoting lists not sets) lead with “Credential”.

These are sets, order is not important.

If we were going to go full on Semantic Web (which we absolutely should not do), and if the machine-readable vocabularies were set up correctly, one could reason that if something is a "ProofOfAgeCredential" that it is a subclass of type "Credential". That said, developers have demonstrated that they're bad at semantics and typically don't publish the sorts of machine readable documents that are required to do this sort of inference.

So, we default to the position that people are going to mess these type systems up, not use them, etc... and that's guiding the spec.

More than likely we'll be strict in what we specify and generous in what we accept.

> The type to the right of “Credential” always seems to be a specialization (subtype ?) of “Credential”.
“Credential”, “DocumentVerfification” and “VerfiableProfile” occur in singleton lists.

Yes, but that's only because the examples are still a bit sloppy. :)

Again, I don't think we've fully committed to the type system being important for interoperability. To state this another way, could we remove `type` completely and the system still operate. I would argue that we could easily do that... we'd specify what properties must exist for a particular piece of logic to execute. It's more difficult than just checking type... but when developers inevitably mark up an important credential and leave out the type, developers will have no choice but to fall back to duck typing and check properties.

That said, perhaps we should just be strict in the document and set the expectation in the hope that software libraries will enforce type checking strictly and we don't fall into the situation of having to duck type production systems.

**Comment by msporny** [comment] 2018-05-19 18:12
@vieillevigne wrote:
> Except for the fact that the object values associated with “claim” properties do not themselves have “type” properties, I’d really like to be able to say that “every object and subobject MUST have a “type” property”. Why don’t, for example, the apparent claim objects have “type” properties?

Claim objects are statements made about a particular subject identifier (sometimes identified by the `id` property). The entity making the claim (issuer) may not have type information and/or may not want to make that sort of claim. For example, a network connected temperature sensor may measure the temperature of a thing in front of it... but it may not know what type of thing that ways... a human, a cow, a truck? So, what should it put if we say that "type" is a MUST? Should it put "Thing"?

So, unfortunately, I think we have to make this "MUST provide a type" distinction on a case by case basis.

**Comment by vieillevigne** [comment] 2018-05-19 18:32
My suggestion then would be that if one does’t know the type of something one should say as much and call  it UNTYPED. Ignorance is really not the default state of the (technical) world.

What Happens Under the Monad Stays Under the Monad.

**Comment by msporny** [comment] 2018-05-19 19:18
> My suggestion then would be that if one does’t know the type of something one should say as much and call  it UNTYPED. Ignorance is really not the default state of the (technical) world.

It's not just ignorance... in some cases, you may not want to specify the type (even if you know it). For example, I know that you're a Person, and I want to associate another attribute with you... and I've already made a statement elsewhere that is public that you are a Person... and I don't want to re-state what I know is obvious.

Remember, because of the data model, all of the claims are merged at some point... so if everyone specifies the type, you just have a large number of people saying you're a Person when almost everyone doesn't need that information to make a decision about you.

The other thing that comes up is, how do you make the distinction between "I don't know the type" and "I'm not going to specify the type". Do you say say something or say nothing?

We've erred on the side of not saying things that won't help decision making. So, for example... saying "UNTYPED" doesn't really help anyone make a decision (except in very esoteric corner cases).

**Comment by vieillevigne** [comment] 2018-05-19 19:32
> 
> In the case of types not used in lists, how do I know that they are not parts of specialization hierarchies elsewhere? Indeed, how do I know that “Credential” does not appear in a specialization hierarchy? Under what circumstance does one use a list for a singleton?
> 
> I don't understand this question... or at least, there is not enough there for me to feel confident that I'll be answering your question and not something else.
> 
The presupposition of the question is that the lists in the examples represent specialization hierarchy. Since you say there is no such hierarchy, the question is based on an evidently false hypothesis.

**Comment by msporny** [comment] 2018-05-19 19:35
> I am particularly puzzled by the assertion at section 5.2 that “A credential MAY be made verifiable by adding the following property …”. This suggests that a credential may be made verifiable in some other way than providing a proof.

That is not what the language is intending to convey... it used to be a "signature", and we changed it to "proof"... which made the language a bit unwieldy. The intent was to say that there is information that is "unverifiable"... and if you add a signature/proof of some kind... it's "verifiable" (for the definition of verifiable that we express in the specification).

>  It also suggests that a credential need not be verifiable at all. 

Yes, you can express information that isn't verifiable (in the mathematical sense)... this has been clarified in PR https://github.com/w3c/vc-data-model/commit/13864d20a6005f0da8ba42f282487160cdb408dd.

> Moreover, the example which immediately follows does have a “proof” property and also has a “ProofOfAgeCredential” type. Why is the latter needed in the presence of the former? 

The latter narrows the type information for the credential.

> What are sufficient conditions to be a verifiable credential? 

The proof field has to exist and contain a valid proof.

> What are necessary conditions to be a verifiable credential? 

The proof field has to exist and contain a valid proof.

> Is it intended that there be credentials which are not verifiable?

Yes, and this has been clarified here in this PR: https://github.com/w3c/vc-data-model/commit/13864d20a6005f0da8ba42f282487160cdb408dd

**Comment by msporny** [comment] 2018-05-19 19:43
@vieillevigne wrote:
> While section 7.2 apparently does say that an object of the “Credential” type MUST have “type” and “claim” properties, it (surprisingly) does not appear to say such a thing for “issuer” and “issued”. 

Yes, as those are optional fields that can be derived from the proof (in most cases). "issuer" and "issued" are provided if that information deviates from the date the proof was issued, or the proof was issued by a delegate of the issuer.

> The meaning of a type is ordinarily understood to derive from its relationships with other types. On that account, it seems unlikely to me that something intended to be a “Credential” does not always have “issuer” and “issued” values. So what properties MUST an object of type “Credential” have?

“type” and “claim” :)

**Comment by msporny** [comment] 2018-05-19 19:49
> A verifiable profile object appears to have no requirement at all on its properties. While EXAMPLE 18, EXAMPLE 22 – apparently verifiable profile objects -- have no “type” property, EXAMPLE 5 does.

Note: We've switched over to language that now, instead of talking about "profiles", talks about "presentations".

Woops! Good catch, thank you! Fixed in https://github.com/w3c/vc-data-model/pull/177/commits/096068ea4a53d3f11fe5c548e36ea0126900becc

> (BTW, the ‘Section’ reference in section 8.2.2 is invisible and it actually points to the top level of the document. Ditto the ‘Section’ reference in 8.2.1.) Is the absence of a “type” an error?

These should be fixed now as a result of a separate set of PRs.

**Comment by msporny** [comment] 2018-05-19 19:51
> “type” appears to be a reserved word in JSON schema. I can imagine some of the parties interested in verifiable claims might also be interested in making use of JSON schema to (partially) specify claims. While the magic of namespaces can allow one to deconflict, might not another keyword be better?

We've been using JSON Schema and Verifiable Credentials together for 7+ years now and have not had an issue. The reason for this is because JSON Schema is often run on JSON-LD objects as they're coming into the system and the two processes operate independently of one another. That is, JSON Schema knows nothing of JSON-LD... and JSON-LD knows how to contort itself such that JSON Schema has no idea that it's looking at JSON-LD. This was by design, and the design seems to be working fairly cleanly 7+ years from when we made those sets of decisions.

**Comment by msporny** [comment] 2018-05-19 19:52
@vieillevigne I think I've responded to every point you raised at this time. It resulted in a new section in the specification via this pull request: https://github.com/w3c/vc-data-model/pull/177

Let me know if you feel that other changes should be made to the specification based on my responses to you.

**Comment by vieillevigne** [comment] 2018-05-19 19:59
> The other thing that comes up is, how do you make the distinction between "I don't know the type" and "I'm not going to specify the type". Do you say say something or say nothing?
> 
The distinction is formally easy to make, There are, for example, any number of logics conceived for knowledge representation purposes in which the distinction between “it is not known that P” and "it is not knowable that P” is syntactically and semantically evident. Null values have been and are used to mean both things in relational databases. There the failure to make the distinction has led to a legion of documented adverse consequences -- some amusing, some tragic. With exactly that history in mind the matter was debated for two years in the XML Schema Working Group. There you had the database folk collide head on with the document folk.

What Happens Under the Monad Stays Under the Monad.
Sent from Allen's Mac Pro

**Comment by msporny** [comment] 2018-05-20 14:56
> There are, for example, any number of logics conceived for knowledge representation purposes in which the distinction between “it is not known that P” and "it is not knowable that P” is syntactically and semantically evident.

Ah, but there are three possibilities: "it is not known that P", "it is not knowable that P", AND "P is known to me, but I do not wish to express it". These can be expressed as such:

1. "it is not known that P" - `"type": "Unknown"`
2. "it is not knowable that P" - `"type": "Unknowable"`
3. "P is known to me, but I do not wish to express it" - This is where you say nothing

The assertion I'm making is that 1 and 2 above are not useful in the general case, and when they are useful, the data model enables those types to be expressed. That said, I know of no RDF vocabulary that defines 1 or 2 (and I'm not certain about why that's the case... but I have a few guesses).

So, yes, if you do this wrong, you can really screw things up (e.g. the difference between how a language maps `null`, `0`, and `undefined` being important when reading data out of a database to an implementation language).

All that said, I don't know if there is an action that we can take as a result of this? I suggest no action at present.

**Comment by msporny** [comment] 2018-06-12 22:37
Closing this issue as a new type section has been added to the spec.

**Closed** 2018-06-12 22:38 UTC
Labels: Type-Discussion
