### ISSUE TITLE
Charter

### ISSUE THREAD

**Issue by nadalin** [w3c/vc-data-model#502] opened 2019-03-27 17:31 UTC
It looks like the WebAuthen WG was missed out of the charter in the Dependencies and Liaisons section., not sure if this was a timing issue on when the groups started or not but the WebAuthn WG should be a Liaison.

Not sure if a charter update can be done at this time, but looks like it should since this was an oversite

**Comment by brentzundel** [comment] 2019-03-29 19:02
It seems to me that if this was really an issue, it should have been brought up before. 
The charter has been around for years, and I'm sure it has had a lot of scrutiny in that time, both from within and outside of the group.
Could you clarify your reasons for believing that the WebAuthn WG should be listed as a liaison to the VCWG? I have been quite active in the VCWG for quite some time and cannot recall any interactions with the WebAuthn WG in that time, so it is not clear to me what you mean.
I'm also not sure if a charter update can be done at this time, but don't yet see that it should be necessary.

**Comment by stonematt** [comment] 2019-04-05 17:55
WG Resolution: https://www.w3.org/2019/04/02-vcwg-minutes.html#resolution07

RESOLUTION: The VCWG notes that the charter cannot be changed at present and thus new Liaison relationships cannot be added. The VCWG also notes and is thankful of the review of the specification that has been performed by Tony Nadalin, who is a co-chair of the WebAuthn WG, and welcomes comments from all interested Working Groups. Issue #513 [minutes indicate issue #502 was intended] should be closed with no change to the specification.

Will close 7 days from today if no new concerns or evidence are raised by then in this issue.

**Comment by nadalin** [comment] 2019-04-08 15:15
@stonematt I don't understand why the charter can't be changed as it can be changed at anytime, there is a process for this. I think this needs to go up to W3C Management to get changed

**Comment by nadalin** [comment] 2019-04-08 19:28
@stonematt Let's say the charter can't be updated, this does not mean that that there is no  Liaison relationships between WebAuthn and VC this can be made to happen outside the charter, so this is my main point that the liaison happen

**Comment by brentzundel** [comment] 2019-04-08 21:17
@nadalin, what specific changes do you recommend, other than changing the charter, which would address this issue?

**Comment by stonematt** [comment] 2019-04-15 13:20
The group discussed this topic and decided not to reopen the charter.  All groups are welcome to comment on the CR, including the WebAuthn WG.

Closing.

**Closed by stonematt** 2019-04-15 13:20 UTC
Labels: Pending 7 Day Close

**Comment by nadalin** [comment] 2019-04-15 17:09
@stonematt This seems odd that this WG is not willing to reach out to the WebAuthn WG for security knowledge and reviews. No sure what the rational is but this should be noted to the TAG

**Comment by brentzundel** [comment] 2019-04-16 16:14
I read this:

> The VCWG also notes and is thankful of the review of the specification that has been performed by Tony Nadalin, who is a co-chair of the WebAuthn WG, and welcomes comments from all interested Working Groups. 

and fail to see how it may be interpreted as this:

> this WG is not willing to reach out to the WebAuthn WG for security knowledge and reviews.

**Comment by nadalin** [comment] 2019-04-16 17:01
@brentzundel Pretty easy  since there was no mention of not changing it at next update point, if that was noted than I would accept but the way it's worded is not in a very collaborative means
